from __future__ import annotations

from typing import Protocol

from app.catalog import StockProfile
from app.providers.mock_provider import MarketSnapshot
from app.providers.models import DailyBar
from app.schemas import DataReadinessItem, SourceLink


class ResearchProvider(Protocol):
    provider_name: str
    provider_mode: str
    degraded_reason: str | None

    def search_stocks(self, query: str, limit: int = 8) -> list[StockProfile]: ...
    def get_stock_profile(self, symbol: str) -> StockProfile: ...
    def related_profiles(self, profile: StockProfile) -> list[StockProfile]: ...
    def market_snapshot(self, profile: StockProfile) -> MarketSnapshot: ...
    def build_source_links(self, profile: StockProfile) -> list[SourceLink]: ...
    def reference_bundle(self, profile: StockProfile) -> dict[str, SourceLink]: ...
    def disclosure_pool(self, profile: StockProfile) -> list[dict[str, object]]: ...
    def community_pool(self, profile: StockProfile) -> list[dict[str, object]]: ...
    def news_pool(self, profile: StockProfile) -> list[dict[str, object]]: ...
    def forum_snapshot(self, profile: StockProfile) -> dict[str, object]: ...
    def data_readiness(self) -> list[DataReadinessItem]: ...
    def get_price_history(self, profile: StockProfile, window_days: int) -> list[DailyBar]: ...
